CREATE DATABASE IF NOT EXISTS books CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE books;

DROP TABLE IF EXISTS books;
CREATE TABLE books (
    id INT AUTO_INCREMENT PRIMARY KEY,
    series VARCHAR(100) NOT NULL,
    title VARCHAR(200) DEFAULT NULL,
    subtitle VARCHAR(255) DEFAULT NULL,
    description TEXT DEFAULT NULL,
    asin VARCHAR(20) NOT NULL UNIQUE,
    language VARCHAR(10) NOT NULL,
    format VARCHAR(20) NOT NULL DEFAULT 'paperback'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO books (series, title, subtitle, description, asin, language, format) VALUES
    ('Strom', 'Strom (DE)', NULL, NULL, 'B0GLZBB5BD', 'DE', 'paperback'),
    ('Strom', 'Strom (EN)', NULL, NULL, 'B0GLY99X85', 'EN', 'paperback'),
    ('Strom', 'Strom (ES)', NULL, NULL, 'B0GLYNXFGV', 'ES', 'paperback'),
    ('Einstein', 'Einstein (DE)', NULL, NULL, 'B0GLZSTNWS', 'DE', 'paperback'),
    ('Einstein', 'Einstein (EN)', NULL, NULL, 'B0GLZRBFCQ', 'EN', 'paperback'),
    ('Einstein', 'Einstein (ES)', NULL, NULL, 'B0GLZNWWLH', 'ES', 'paperback'),
    ('Parken', 'Parken (DE)', NULL, NULL, 'B0FVM8H7XJ', 'DE', 'paperback'),
    ('Parken', 'Parken (EN)', NULL, NULL, 'B0FTX388L2', 'EN', 'paperback'),
    ('Parken', 'Parken (ES)', NULL, NULL, 'B0FTW32PBK', 'ES', 'paperback'),
    ('Parken', 'Parken (PT)', NULL, NULL, 'B0FVVBRQ7C', 'PT', 'paperback'),
    ('Parken', 'Parken (FR)', NULL, NULL, 'B0FTZRK1ZH', 'FR', 'paperback'),
    ('Parken', 'Parken (IT)', NULL, NULL, 'B0FVM8NHVV', 'IT', 'paperback'),
    ('Parken', 'Parken (SV)', NULL, NULL, 'B0FTTCFL31', 'SV', 'paperback'),
    ('Parken', 'Parken (NL)', NULL, NULL, 'B0FVNJ22JX', 'NL', 'paperback'),
    ('Technik', 'Technik (DE)', NULL, NULL, 'B0FVVZFNG6', 'DE', 'paperback'),
    ('Technik', 'Technik (EN)', NULL, NULL, 'B0FVVXL7ZY', 'EN', 'paperback'),
    ('Technik', 'Technik (ES)', NULL, NULL, 'B0FVWNN86L', 'ES', 'paperback'),
    ('Technik', 'Technik (PT)', NULL, NULL, 'B0FVVC6H6Q', 'PT', 'paperback'),
    ('Technik', 'Technik (FR)', NULL, NULL, 'B0FW71VST3', 'FR', 'paperback'),
    ('Technik', 'Technik (IT)', NULL, NULL, 'B0FWB441RS', 'IT', 'paperback'),
    ('Technik', 'Technik (SV)', NULL, NULL, 'B0FW6P1D51', 'SV', 'paperback'),
    ('Technik', 'Technik (NL)', NULL, NULL, 'B0FW6GYYRK', 'NL', 'paperback'),
    ('Reisen', 'Reisen (DE)', NULL, NULL, 'B0FWKK7RJ6', 'DE', 'paperback'),
    ('Reisen', 'Reisen (EN)', NULL, NULL, 'B0FWC7DG94', 'EN', 'paperback'),
    ('Reisen', 'Reisen (ES)', NULL, NULL, 'B0FXBFV2RP', 'ES', 'paperback'),
    ('Reisen', 'Reisen (PT)', NULL, NULL, 'B0FXBDL4W3', 'PT', 'paperback'),
    ('Reisen', 'Reisen (FR)', NULL, NULL, 'B0FXBKGC2Z', 'FR', 'paperback'),
    ('Reisen', 'Reisen (IT)', NULL, NULL, 'B0FXBGDVTF', 'IT', 'paperback'),
    ('Reisen', 'Reisen (SV)', NULL, NULL, 'B0FXBCSGHP', 'SV', 'paperback'),
    ('Reisen', 'Reisen (NL)', NULL, NULL, 'B0FXB5M1YT', 'NL', 'paperback'),
    ('Kundendienst', 'Kundendienst (DE)', NULL, NULL, 'B0FY2GTVBH', 'DE', 'paperback'),
    ('Kundendienst', 'Kundendienst (EN)', NULL, NULL, 'B0FXRFL61D', 'EN', 'paperback'),
    ('Kundendienst', 'Kundendienst (ES)', NULL, NULL, 'B0FY39PNS4', 'ES', 'paperback'),
    ('Kundendienst', 'Kundendienst (PT)', NULL, NULL, 'B0FY32TM8D', 'PT', 'paperback'),
    ('Kundendienst', 'Kundendienst (FR)', NULL, NULL, 'B0FY2P1PTX', 'FR', 'paperback'),
    ('Kundendienst', 'Kundendienst (IT)', NULL, NULL, 'B0FY38ZYBQ', 'IT', 'paperback'),
    ('Kundendienst', 'Kundendienst (SV)', NULL, NULL, 'B0FY36DLKC', 'SV', 'paperback'),
    ('Kundendienst', 'Kundendienst (NL)', NULL, NULL, 'B0FY2GX6H6', 'NL', 'paperback'),
    ('Nachbarn', 'Nachbarn (DE)', NULL, NULL, 'B0FZHBF28C', 'DE', 'paperback'),
    ('Nachbarn', 'Nachbarn (EN)', NULL, NULL, 'B0FT1D19Y2', 'EN', 'paperback'),
    ('Nachbarn', 'Nachbarn (ES)', NULL, NULL, 'B0FZHR1373', 'ES', 'paperback'),
    ('Nachbarn', 'Nachbarn (PT)', NULL, NULL, 'B0FZHFCM7G', 'PT', 'paperback'),
    ('Nachbarn', 'Nachbarn (FR)', NULL, NULL, 'B0FZHMJ25C', 'FR', 'paperback'),
    ('Nachbarn', 'Nachbarn (IT)', NULL, NULL, 'B0FYW5KQTN', 'IT', 'paperback'),
    ('Nachbarn', 'Nachbarn (SV)', NULL, NULL, 'B0FZHQ1J19', 'SV', 'paperback'),
    ('Nachbarn', 'Nachbarn (NL)', NULL, NULL, 'B0FYQF725J', 'NL', 'paperback'),
    ('Finanzen', 'Finanzen (DE)', NULL, NULL, 'B0G1BRXKXK', 'DE', 'paperback'),
    ('Finanzen', 'Finanzen (EN)', NULL, NULL, 'B0G1K7R5V2', 'EN', 'paperback'),
    ('Finanzen', 'Finanzen (ES)', NULL, NULL, 'B0G1K4JG3H', 'ES', 'paperback'),
    ('Finanzen', 'Finanzen (PT)', NULL, NULL, 'B0G1K8LLW6', 'PT', 'paperback'),
    ('Finanzen', 'Finanzen (FR)', NULL, NULL, 'B0G1K4C4TL', 'FR', 'paperback'),
    ('Finanzen', 'Finanzen (IT)', NULL, NULL, 'B0G1K7XRX5', 'IT', 'paperback'),
    ('Finanzen', 'Finanzen (SV)', NULL, NULL, 'B0G1JT7BTG', 'SV', 'paperback'),
    ('Finanzen', 'Finanzen (NL)', NULL, NULL, 'B0G1K8B75J', 'NL', 'paperback'),
    ('Behörden', 'Behörden (DE)', NULL, NULL, 'B0G2YVNNLQ', 'DE', 'paperback'),
    ('Behörden', 'Behörden (EN)', NULL, NULL, 'B0G2YF4DDF', 'EN', 'paperback'),
    ('Behörden', 'Behörden (ES)', NULL, NULL, 'B0G2YM5GHF', 'ES', 'paperback'),
    ('Behörden', 'Behörden (PT)', NULL, NULL, 'B0G2YMFD8G', 'PT', 'paperback'),
    ('Behörden', 'Behörden (FR)', NULL, NULL, 'B0G2YKGLP4', 'FR', 'paperback'),
    ('Behörden', 'Behörden (IT)', NULL, NULL, 'B0G2YLSQG3', 'IT', 'paperback'),
    ('Behörden', 'Behörden (SV)', NULL, NULL, 'B0G2YSNVVD', 'SV', 'paperback'),
    ('Behörden', 'Behörden (NL)', NULL, NULL, 'B0G33H6BCJ', 'NL', 'paperback'),
    ('Dating', 'Dating (DE)', NULL, NULL, 'B0G3XCF73Q', 'DE', 'paperback'),
    ('Dating', 'Dating (EN)', NULL, NULL, 'B0GM5YSVB3', 'EN', 'paperback'),
    ('Dating', 'Dating (ES)', NULL, NULL, 'B0G3XBK7LY', 'ES', 'paperback'),
    ('Dating', 'Dating (PT)', NULL, NULL, 'B0G3XBNHV7', 'PT', 'paperback'),
    ('Dating', 'Dating (FR)', NULL, NULL, 'B0G3VMQ7Y8', 'FR', 'paperback'),
    ('Dating', 'Dating (IT)', NULL, NULL, 'B0G3XCGQ83', 'IT', 'paperback'),
    ('Dating', 'Dating (SV)', NULL, NULL, 'B0G3XD4N7C', 'SV', 'paperback'),
    ('Dating', 'Dating (NL)', NULL, NULL, 'B0G3WGDWPM', 'NL', 'paperback'),
    ('Gericht', 'Gericht (DE)', NULL, NULL, 'B0G5FG453Y', 'DE', 'paperback'),
    ('Gericht', 'Gericht (EN)', NULL, NULL, 'B0G58PWWPK', 'EN', 'paperback'),
    ('Gericht', 'Gericht (ES)', NULL, NULL, 'B0G58WXJKS', 'ES', 'paperback'),
    ('Gericht', 'Gericht (PT)', NULL, NULL, 'B0G593ZQYT', 'PT', 'paperback'),
    ('Gericht', 'Gericht (FR)', NULL, NULL, 'B0G58YG8GQ', 'FR', 'paperback'),
    ('Gericht', 'Gericht (IT)', NULL, NULL, 'B0G58XQ33H', 'IT', 'paperback'),
    ('Gericht', 'Gericht (SV)', NULL, NULL, 'B0G5F5S8MS', 'SV', 'paperback'),
    ('Gericht', 'Gericht (NL)', NULL, NULL, 'B0G58SRN3G', 'NL', 'paperback'),
    ('Gesundheit', 'Gesundheit (DE)', NULL, NULL, 'B0GCGXLDBL', 'DE', 'paperback'),
    ('Gesundheit', 'Gesundheit (EN)', NULL, NULL, 'B0GCH5B5JR', 'EN', 'paperback'),
    ('Gesundheit', 'Gesundheit (ES)', NULL, NULL, 'B0GCHRCG58', 'ES', 'paperback'),
    ('Gesundheit', 'Gesundheit (PT)', NULL, NULL, 'B0GCH6W2D8', 'PT', 'paperback'),
    ('Gesundheit', 'Gesundheit (FR)', NULL, NULL, 'B0GCJNW756', 'FR', 'paperback'),
    ('Gesundheit', 'Gesundheit (IT)', NULL, NULL, 'B0GCHWKHLN', 'IT', 'paperback'),
    ('Gesundheit', 'Gesundheit (SV)', NULL, NULL, 'B0GCH6XH99', 'SV', 'paperback'),
    ('Gesundheit', 'Gesundheit (NL)', NULL, NULL, 'B0GCHW9LDK', 'NL', 'paperback'),
    ('Familie', 'Familie (DE)', NULL, NULL, 'B0GFLPSRJ3', 'DE', 'paperback'),
    ('Familie', 'Familie (EN)', NULL, NULL, 'B0GFJV4SFF', 'EN', 'paperback'),
    ('Familie', 'Familie (ES)', NULL, NULL, 'B0GFK23NS4', 'ES', 'paperback'),
    ('Familie', 'Familie (PT)', NULL, NULL, 'B0GFLF6J8Z', 'PT', 'paperback'),
    ('Familie', 'Familie (FR)', NULL, NULL, 'B0GFLR1GM9', 'FR', 'paperback'),
    ('Familie', 'Familie (IT)', NULL, NULL, 'B0GFK7VN2Y', 'IT', 'paperback'),
    ('Familie', 'Familie (SV)', NULL, NULL, 'B0GFLWVVYR', 'SV', 'paperback'),
    ('Familie', 'Familie (NL)', NULL, NULL, 'B0GFK8R23T', 'NL', 'paperback'),
    ('Ausreden', 'Ausreden (DE)', NULL, NULL, 'B0GD7DHJFH', 'DE', 'paperback'),
    ('Ausreden', 'Ausreden (EN)', NULL, NULL, 'B0GD62D964', 'EN', 'paperback'),
    ('Ausreden', 'Ausreden (ES)', NULL, NULL, 'B0GD7893MV', 'ES', 'paperback'),
    ('Ausreden', 'Ausreden (PT)', NULL, NULL, 'B0GD76W5FM', 'PT', 'paperback'),
    ('Ausreden', 'Ausreden (FR)', NULL, NULL, 'B0GD7CDMSS', 'FR', 'paperback'),
    ('Ausreden', 'Ausreden (IT)', NULL, NULL, 'B0GD7M48ZF', 'IT', 'paperback'),
    ('Ausreden', 'Ausreden (SV)', NULL, NULL, 'B0GD7GSNMR', 'SV', 'paperback'),
    ('Ausreden', 'Ausreden (NL)', NULL, NULL, 'B0GD7CCPQY', 'NL', 'paperback');
